### ISSUE TITLE
Issue in running benchmark

### ISSUE THREAD

**Issue by PouyaKhn** [zoeparman/benchmark-general-imaging#4]
Hi, when I want to run a benchmark, this error occured:
"
Traceback (most recent call last):
  File "scripts/run_benchmark.py", line 5, in <module>
    from .util.dataset_models import get_dataset_model
ImportError: attempted relative import with no known parent package
"
in run_benchmark.py file, there are two lines of code for importing some requirement packages:

from .util.dataset_models import get_dataset_model
from .util import MethodLoader

I think ".util" folder is not exist in files, and this is the cause of this issue. Can you propose a solution for this problem?

**Comment by arnegevaert** [comment]
Hi,

It seems that indeed some files were accidentally added to .gitignore.
I have now added them back in a hotfix, it should work again.
Note that we are working on a new implementation of the benchmark itself (https://github.com/arnegevaert/benchmark) that can run on multiple GPUs, so there might still be some other instabilities.
However, if you use `requirements_old.txt` to create a virtual environment, it should work.
I will add a release in this project when it is compatible again with the latest version of the benchmark.
